version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meca-api-main-container
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped
